<?php
/**
 * Created by PhpStorm.
 * User: home
 * Date: 22.09.2021
 * Time: 11:36
 */

namespace App\Pages;

class ComponentTotal extends \App\Pages\ComponentProd
{
    public function __construct($id)
    {
        parent::__construct($id);
    }

    public function getContent($attributes)
    {
        $arr = $this->value;
        $drr = $arr->total;
        $total = $arr->total_qty;
        $brr = [];
        $done = [];
        $need = [];
        $done[] = "всего сделано";
        $need[] = "нужно сделать";
        $head[] = "";
        foreach ($drr as $d=>$v){
            $head[] = $d;
            $done[] = $v;
            $need[] = $total - $v;
        }
        $brr[] = $head;
        $brr[] = $done;
        $brr[] = $need;

        $row = count($brr);
        $col = count($brr[0]);
        $data = "master";
        $this->str = $this->createTable($row, $col, $brr, "", "total");
//        $this->str = "<p>Total</p>";
        return $this->str;
        //return parent::getContent($attributes); // TODO: Change the autogenerated stub
    }
}