<?php
/**
 * Created by PhpStorm.
 * User: home
 * Date: 06.09.2021
 * Time: 20:46
 */

namespace App\Pages;

use App\Application as App;
use App\Entity\Item;
use Zippy\Binding\PropertyBinding as  Bind;
use App\Helper as H;
use App\System;
use Zippy\Html\DataList\ArrayDataSource;
use Zippy\Html\DataList\DataView;
use Zippy\Html\Form\AutocompleteTextInput;
use Zippy\Html\Form\Button;
use Zippy\Html\Form\CheckBox;
use Zippy\Html\Form\DropDownChoice;
use Zippy\Html\Form\Form;
use Zippy\Html\Form\SubmitButton;
use Zippy\Html\Form\TextArea;
use Zippy\Html\Form\TextInput;
use Zippy\Html\Label;
use Zippy\Html\Link\ClickLink;
use Zippy\Html\Panel;
use Zippy\Html\Link\SubmitLink;


class PasportItem extends \App\Pages\Base
{
    public $numb = 1;
    public $pg_size;
    public $str_items;
    public function __construct($params = null)
    {
        parent::__construct($params);

//        if (false == \App\ACL::checkShowRef('ItemList')) {
//            return;
//        }
        $this->str_items = $params;
        $this->pg_size = 10;
        $this->add(new Panel('itemtable'))->setVisible(true);
        $this->itemtable->add(new Form('listform')) ;

        $this->itemtable->listform->add(new DataView('itemlist', new ItemDataTest($this), $this, 'itemlistOnRow'));//->Reload();
        $this->itemtable->listform->itemlist->setPageSize($this->pg_size);//H::getPG()
        $this->itemtable->listform->add(new \Zippy\Html\DataList\Paginator('pag', $this->itemtable->listform->itemlist));
        $this->itemtable->listform->itemlist->setSelectedClass('table-success');
        $this->itemtable->listform->add(new SubmitLink('saveMaterial'))->onClick($this, 'saveMaterialOnClick');
        $this->itemtable->listform->add(new SubmitLink('cancelMaterial'))->onClick($this, 'saveMaterialOnClick');

        $this->itemtable->listform->itemlist->Reload();
    }

    public function itemlistOnRow(\Zippy\Html\DataList\DataRow $row) {
        $item = $row->getDataItem();

        $row->add(new Label('typeMaterial', $item->itemname));
        $row->add(new Label('typeUnit',  $item->msr));
        $row->typeMaterial->setAttribute('data-itemid', $item->item_id);
        $pag_search = $_GET['q'];
        $match = [];
        $r = preg_match('/pag:\d{1,}/i', $pag_search, $match);
        if($r == false){
            $row->add(new TextInput('quantity'));
        }else{
            $pag_parse = explode(":", $match[0]);
            $key = 'quantity_' . $pag_parse[1] . '_' . $this->numb . "_" . $item->item_id;

            if(array_key_exists($key, $_SESSION) == true){
                $row->add(new TextInput('quantity', $_SESSION[$key]));
                unset($_SESSION[$key]);
            }else{
                $row->add(new TextInput('quantity'));
            }

            $this->numb++;
        }
        $row->quantity->setAttribute('data-itemid', $item->item_id);

        $row->add(new \Zippy\Html\Link\BookmarkableLink('imagelistitem'))->setValue("/loadimage.php?id={$item->image_id}");
        $row->imagelistitem->setAttribute('href', "/loadimage.php?id={$item->image_id}");
        $row->imagelistitem->setAttribute('data-gallery', $item->image_id);
        if ($item->image_id == 0) {
            $row->imagelistitem->setVisible(false);
        }
    }

    public function beforeRequest()
    {
        parent::beforeRequest(); // TODO: Change the autogenerated stub
        $this->numb = 1;
    }

    public function saveMaterialOnClick($sender){
        $text = "";
        if($sender->id == 'saveMaterial'){
            $conn = \ZDB\DB::getConnect();
            $sql = "SELECT itemname, item_id FROM items WHERE cat_id=9 ORDER BY 1";
            $rs = $conn->Execute($sql);
            $material = [];
            foreach ($rs as $r){
                $material[] = $r['itemname'];
            }
            $page_search = $_GET['q'];
            $match = [];
            $r = preg_match('/pag:\d{1,}/i', $page_search, $match);
            $pag_parse = explode(":", $match[0]);
            $pag_num = $pag_parse[1];

            $sessions = $_SESSION;
            foreach ($sessions as $key=>$val){
                if(str_starts_with($key, "quantity") == true){
                    $parse = explode("_", $key);
                    if($parse[1] != $pag_num){
                        $str_mat = $material[(intval($parse[1])-1) * ($this->pg_size) + intval($parse[2])-1];
                        //$text .= $str_mat . " (" . $val . ")|(" . $parse[3] . ")|,";
                        $text .= $str_mat . " <" . $val . ">|(" . $parse[3] . ")|,";
                    }
                }
            }
            $listmaterial = $this->itemtable->listform->itemlist->getChildComponents();

            foreach ($listmaterial as $mat){
                $itemmaterial = $mat->getChildComponents();
                foreach ($itemmaterial as $k=>$v){
                    if(str_starts_with($k, "typeMaterial") == true){
                        $sk = explode("_", $k);
                        $p = "quantity_" . $sk[1];
                        $value = $itemmaterial[$p]->getText();
                        $item_id = $itemmaterial[$p]->getAttribute('data-itemid');
                        if($value != "" && $value != 0){
                            $text .= $v->getText();
                            // $text .= " (" . $value . ")|(" . $item_id . ")|,";
                            $text .= " <" . $value . ">|(" . $item_id . ")|,";
                        }
                    }
                }
            }
        }
//        foreach ($_SESSION as $key=>$sess){
//            if(str_starts_with($key, 'quantity') == true){
//                unset($_SESSION[$key]);
//            }
//        }
        App::Redirect("\\App\\Pages\\Pasport", $text . "::" . $this->str_items);
    }
}

class ItemDataTest implements \Zippy\Interfaces\DataSource
{

    private $page;

    public function __construct($page) {
        $this->page = $page;
    }

    private function getWhere($p = false) {
        $where = "1=1";
        $cat = 9;

        if ($cat != 0) {
            if ($cat == -1) {
                $where = $where . " and cat_id=0";
            } else {
                $where = $where . " and cat_id=" . $cat . " and disabled = false";
            }
        }
        return $where;
    }

    public function getItemCount() {
        return Item::findCnt($this->getWhere());
    }

    public function getItems($start, $count, $sortfield = null, $asc = null) {
        $l = Item::find($this->getWhere(true), "itemname asc", $count, $start);
        $f = Item::find($this->getWhere(), "itemname asc", $count, $start);

        foreach ($f as $k => $v) {
            $l[$k] = $v;
        }
        return $l;
    }

    public function getItem($id) {
        return Item::load($id);
    }

}